### ISSUE TITLE
tile builder/spec v0.2 update

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/sharedstreets-builder#10]
cc @migurski @DenisCarriere  

Making a list of changes for the v0.2 re of the tile builder. Current changes include:

- [x] Add street names to OSM metadata output (#9) 
- [x] Add "living street" tag to included roads (#7)
- [x] Exclude Parking Aisles (#8 )
- [x] Reduce precision of hashes to five decimals for lat/lng (~1m+/- at worst) and 1m for distance (per sharedstreets/sharedstreets-js/issues/16)
- [ ] ....?

Curious if we should add hierarchical filtering of road network based on OSM classification -- or shift that to the client libraries (currently leaning toward implementing in the client).

**Comment by DenisCarriere** [comment]
👍 I'll update the Javascript library to reflect five decimals and 1m for distances

**Comment by kpwebb** [comment]
@DenisCarriere and @migurski the new v0.2 tiles are up at

https://tiles.sharedstreets.io/planet-180311/

Let me know once you' have a chance check and I'll switch the API end point to make these at the default, and cut a formal release for ss-builder!

Also, FYI, keeping old tiles and generating more  historical versions from past OSM planet files to aid in OMS QA process.

**Comment by migurski** [comment]
Thanks @kpwebb, working on it!

By the way, we’re seeing CORS errors at https://platform.sharedstreets.io/37.81262/-122.26065/16.754/

**Comment by migurski** [comment]
Followup: we would need new versions of the `.proto` file and generated Python code, is that right?

**Comment by kpwebb** [comment]
If you want to take advantage of the new fields for  street names, yes, but new data should be backwards compatible. Let me know if you see issues.

**Comment by kpwebb** [comment]
@migurski see ^^^^  Also not seeing CORS issues -- can you post what you're seeing? I did witness some odd errors fetch via CURL from CloudFront earlier today, but wasn't able to track down cause.

**Comment by migurski** [comment]
I have a PR above for the new tile versions. The v0.2 ones look great, feel free to cut over whenever you want. 

I also went back and checked for CORS errors and whatever we were seeing is not a problem anymore/

**Comment by kpwebb** [comment]
Just adding this as an FIY re CORS. We've been intermittently encountering CORS failures via CloudFront. 

Here's why:

https://serverfault.com/questions/856904/chrome-s3-cloudfront-no-access-control-allow-origin-header-on-initial-xhr-req
